Engineer Quest
TheOldRealms/TOW_Core pull request #239
Opened 2022-03-29 00:51 UTC by Z3rca

This is the first iteration for the engineer quest. The cultist quest and engineering quest can be started from the dialog with engineer, it rewards the player with some gold and XP, aswell as unlocking the shop. The phases of the quest are serialized. It follows about (with some efficiency refinements) the logic of the dialog.
 The quest parties are both depending on the QuestPartyComponent. However some refinements are made to be able to spawn a quest party without a leader ( a custom bandit party so to say) .
There are some issues that needs to be investigated :
The end dialog for the rogue engineer requires a single line executed with an event trick (SkipDialog() in RogueEnginerQuest), but replaced with required dying monolog of the enemy. The usual imprisonment dialog is skipped with that, which has some design implications, if the player must execute the imprisoned lord (it is undesired, might restrict the outcome of a quest) or even gameplay and game logic wise (executions are considered cruel, lords start to hate you for this behavior). The dying monolog prevents the imprisonment and removes the party after battle.
The parties are also removed when the quest is failed. In case of the cultists, it shows an imprisonment screen, but the player is released immediately, and the party disappears. 

Known issues:
Quest dialog is currently a little bit confusing. I would like to have some input how dialog ids should be named. The all-small letters convention is not well readable I would prefer maybe a “_” or “camelCase” convention. I for now separated for each character in the dialog, but especially for the engineer, the dialog lines look like a mess. If somebody has a better idea to structure this, I am more than happy to hear. Also, I have the impression some checks are not necessary but I am not sure what. Depending on the order and the priority maybe some checks could be redundant, I am however not sure how priorities work.
On reloading the game, the parties are removed and reinstantiated in the first update cycle. This workaround was needed to make the party visible on the world map again, I assume a bug of taleworlds. For the non-lord cultist party, sometimes the parties are still marked (?) after reload and disappear then for a frame, but sometimes not at all.  For the lord party, this doesn’t work at all, so the party is not marked anymore. Respawning the party works with the additional scripts completely fine in the logic of the quest, but the party is removed visible for the player ( “Goswin is lost”), I have no clue how the source of the problem can be fixed, so we might harmony patch the symptoms.

After some comments, I might clean up the code more and comment it thoroughly. Please don’t hesitate to test and give me some feedback.

For later
I have a strong urge to refactor the Questparty logic. It would however require some additional changes, that would make this PR way messier. If we can say this system work reliable, we should maybe create a more generalized logic for it, that can be used for what ever quest. In the PR you might find some variables that are less needed, e.g., the optional renaming of a Party and the change of the signature for allowing to define XP and Gold gain, what could be maybe also done directly in position. Here I was experimenting around with some generalized Quest logic.

2022-03-29 15:32 UTC, hunharibo requested changes
Left comments. Overall for now the split into 2 quests design can stay just because of time constraints, but overall you can use questtaskbase fields to mark individual steps being succesful or failed. No need to create separate quests just because of this (-> repeatable parts within a single quest).

2022-03-29 15:32 UTC, hunharibo commented on CSharpSourceCode/CampaignSupport/TownBehaviours/QuestPartyBehavior.cs
> +}
This seems like the entire file is completely unnecessary. It is empty and is not even being added from submodule.cs

2022-03-29 15:32 UTC, hunharibo commented on CSharpSourceCode/Quests/CultistQuest.cs
> +        }
I would not do this. This is a hack for spawning the party again after game load with the sole purpose of having the marker appear?

2022-03-29 15:32 UTC, hunharibo commented on CSharpSourceCode/Quests/InitialEngineerQuest.cs
> +﻿
Entire class is commented out. If it is unneeded, remove it completely please.

2022-03-29 15:32 UTC, hunharibo commented on CSharpSourceCode/Quests/QuestPartyComponent.cs
> +        }
this is not doing anything, what is the purpose of this?

2022-03-29 15:32 UTC, hunharibo commented on CSharpSourceCode/Quests/QuestPartyComponent.cs
> +            component._name = new TextObject(name);
check name being null first? default value is null and you are assigning it without checking.

2022-03-29 15:32 UTC, hunharibo commented on CSharpSourceCode/Quests/RogueEngineerQuest.cs
> +            _initAfterReload = true;
same as with the other quest. Find the root cause instead of this hack?

2022-03-29 15:32 UTC, hunharibo commented on CSharpSourceCode/Quests/RogueEngineerQuest.cs
> +            return _enemyHeroName;
propose to make these getter properties instead of methods

2022-03-29 15:32 UTC, hunharibo commented on CSharpSourceCode/Quests/QuestPartyComponent.cs
> +            component._owner = settlement.Owner;
as discussed on discord, i think this is a potential risk. The owner of a settlement is not going to be part of the party's memberroster. It can become null independent of the party being protected. I suggest to not create parties without explicit leader heros.

2022-03-30 12:15 UTC, Z3rca commented on CSharpSourceCode/Quests/CultistQuest.cs
> +        }
I guess I am happier to remove it, but so far I didn't found a way to get the marker back. It seems to be necessary to add these markers on the initialization of the party and can't be added on runtime.

2022-03-30 12:23 UTC, Z3rca commented on CSharpSourceCode/Quests/QuestPartyComponent.cs
> +        }
removed, sorry was playing around and forgot this method

2022-03-30 12:26 UTC, Z3rca commented on CSharpSourceCode/CampaignSupport/TownBehaviours/QuestPartyBehavior.cs
> +}
was removed, sorry should have payed attention to it

2022-03-30 17:03 UTC, Z3rca commented on CSharpSourceCode/Quests/InitialEngineerQuest.cs
> +﻿
removed

2022-04-02 09:54 UTC, hunharibo approved these changes
Lets get this merged.

2022-04-02 09:56 UTC, merged